// ============================================================================
// 🗄️ BANCO DE DADOS ESTÁTICO DO SANTUÁRIO (CATÁLOGOS E TEXTOS)
// ============================================================================

var BIBLIOTECA_RELIQUIAS = {
    ceu: [
        "Enquanto o sol se põe no horizonte de Goiânia, as primeiras estrelas aparecem aqui em Colombo. É o mesmo céu, apenas em tempos diferentes.",
        "A lua que ilumina as ruas de Goiânia hoje é a mesma que reflete nos meus olhos aqui. Estamos sob o mesmo teto universal.",
        "A distância entre nossas coordenadas geográficas é grande, mas a luz das estrelas não conhece fronteiras. Olhe para cima, eu estou lá com você.",
        "Mesmo que o clima em Colombo seja diferente do calor de Goiânia, o universo que nos envolve é um só. Sinta a conexão no ar.",
        "Cada constelação que cruza o meridiano hoje leva um pensamento meu até você. O céu é o nosso correio sentimental.",
        "Não importa o fuso ou a distância: se ambos olharmos para o alto agora, nossos olhares se cruzam no infinito.",
        "O ciclo hídrico, as nuvens que viajam... tudo o que flutua acima de nós prova que nada está realmente separado.",
        "Goiânia tem o seu brilho, Colombo tem o meu silêncio, mas o céu de hoje une nossas essências em uma só moldura.",
        "A física explica a distância, mas o céu prova a unidade. Somos dois pontos sob a mesma abóbada celeste.",
        "Que a imensidão do céu de hoje te lembre que o meu amor por você não tem limites cartográficos.",
        "O céu de Colombo hoje sobra um vento sul que carrega o meu 'eu te amo' até o calor de Goiânia.",
        "As estrelas são os pontos de GPS que o destino traçou para que nossas almas nunca se perdessem.",
        "A mesma lua que ilumina sua leitura do Vade Mecum é a que brilha sobre meus mapas de solo.",
        "A distância é uma grandeza física; nosso amor é uma constante universal que o céu apenas molda.",
        "Se o céu fosse um tribunal, a lua seria a testemunha ocular de que não passo um minuto sem te desejar.",
        "Não existe nuvem pesada o suficiente para esconder o brilho que você emana no meu horizonte.",
        "Olhar para o alto é o meu ritual de proximidade; o universo é o nosso ponto de encontro oficial.",
        "Enquanto a terra gira, meu pensamento orbita você como um satélite em sintonia perfeita.",
        "O céu hoje tem a cor da paz que sinto quando ouço a sua voz através das ondas do espaço.",
        "Somos dois pontos em estados diferentes, mas sob a mesma cúpula de infinito. Nada nos separa.",
        "A atmosfera entre nós não é vácuo, é preenchida por uma saudade que se converte em força.",
        "Que o brilho de Sirius hoje te lembre que a luz mais forte da minha vida vem de Goiânia.",
        "O pôr do sol é o ensaio geral para o dia em que o veremos juntos, sem telas entre nós.",
        "A astronomia explica os astros; o que eu sinto por você explica o porquê de eles brilharem.",
        "Cada estrela hoje é um pixel da imagem do futuro que estou construindo ao seu lado.",
        "O céu não é o limite para nós; é apenas o cenário onde nossa história é escrita com luz.",
        "Goiânia e Colombo dividem o mesmo meridiano de afeto. O tempo para nós é sempre agora.",
        "Sinta a brisa: é a atmosfera fazendo o intercâmbio de suspiros entre o meu peito e o seu.",
        "A imensidão do céu é o único lugar que comporta a grandiosidade do que sinto por você.",
        "Nossas coordenadas são diferentes, mas o nosso zênite é o mesmo: a felicidade mútua.",
        "O céu noturno é o pergaminho onde as constelações desenham o nosso 'para sempre'.",
        "A luz que viajou anos-luz para chegar aqui hoje é jovem perto da eternidade do nosso amor.",
        "Não importa o quão longe o horizonte pareça, ele sempre termina onde você começa.",
        "O céu de hoje é um espelho: ele reflete a beleza que eu vejo em você todos os dias.",
        "Mesmo que o tempo mude, minha lealdade a você é tão fixa quanto a Estrela Polar.",
        "O firmamento é o nosso teto compartilhado enquanto nossa casa física ainda está em obras no destino.",
        "A vastidão acima de nós é a prova de que para o amor, não existe território proibido.",
        "Beije a lua com o olhar; eu farei o mesmo daqui e nos encontraremos no reflexo dela.",
        "O céu de hoje é o prefácio do livro que escreveremos quando a distância for apenas uma lembrança.",
        "Você é o sol do meu sistema particular; tudo em mim gravita ao redor da sua existência.",
        "O satélite que mapeia as terras lá do alto é o mesmo que captura a intensidade do meu pensamento em você agora.",
        "A umidade do ar em Colombo hoje é saudade condensada, esperando o sol de Goiânia para se transformar em reencontro.",
        "O céu não tem cercas nem divisas; ele é a prova de que nosso amor é um território livre de qualquer embargo.",
        "As ondas de rádio cruzam o país, mas é o brilho da lua que faz o download direto do meu coração para o seu.",
        "Se a distância fosse medida em anos-luz, o céu de hoje diria que já chegamos ao nosso destino final: um ao lado do outro.",
        "O vento que sobra no Sul hoje é o mensageiro que leva o oxigênio da minha vida para alimentar os seus sonhos aí.",
        "Cada estrela cadente é uma petição de urgência que envio ao universo para que o tempo acelere até o nosso abraço.",
        "A estratosfera é o único lugar vasto o suficiente para guardar o arquivo completo de tudo o que planejamos juntos.",
        "Olhe para o horizonte: onde a terra parece terminar, é onde a nossa história ganha a imensidão do infinito.",
        "O sol de hoje realiza a fotossíntese da minha alma, mas é o brilho dos seus olhos que me dá a energia para crescer.",
        "Não existe fuso horário para o afeto; sob este céu, o meu relógio biológico bate no ritmo da sua respiração.",
        "A luz zodiacal de hoje é o reflexo do ouro que você plantou na minha vida. Você é o meu maior tesouro sob o firmamento.",
        "O céu é o diário oficial do nosso amor, onde cada nuvem desenha uma cláusula de felicidade eterna.",
        "Mesmo que o tempo tente nos separar, o céu de hoje é a prova de que estamos sempre juntos, olhando para o mesmo infinito.",
        "A distância é apenas um número; o céu é a prova de que para o amor, não existem fronteiras geográficas."
    ],
    sementes: [
        "Nosso amor não é uma cultura de ciclo curto; é uma floresta perene. Suas raízes já atingiram o lençol freático da minha alma.",
        "Como uma semente que rompe o solo, nosso sentimento venceu a distância e a força maior para florescer no Santuário.",
        "Você é a cláusula pétrea do meu coração. Não cabe emenda, não cabe revisão, apenas o cumprimento integral do nosso afeto.",
        "O veredito da minha vida foi dado no dia em que te conheci: culpado por te amar além de qualquer jurisdição.",
        "A produtividade do meu coração atinge recordes toda vez que recebo um sinal seu. Você é o meu melhor insumo.",
        "Nossa conexão é como um solo de alta fertilidade: exige cuidado, mas a colheita é a mais doce que a vida já produziu.",
        "Mesmo sem o toque físico, nossa fotossíntese acontece através das palavras. Você é a luz que aciona o meu crescimento.",
        "O Vade Mecum do meu afeto tem apenas uma lei: o bem-estar da Thamiris acima de todas as coisas.",
        "Não há embargo que impeça o crescimento do que plantamos. Nossa história é solo protegido, área de preservação permanente.",
        "A logística do destino pode ser complexa, mas a colheita do nosso primeiro abraço será o evento do século.",
        "Você é a semente mais rara: aquela que floresce no deserto da distância e perfuma toda a minha vida.",
        "O solo do meu coração foi preparado com paciência para receber a cultura mais preciosa: você.",
        "Nossa conexão é cláusula pétrea: não admite revisão, não admite retrocesso, apenas soberania.",
        "Como um agrônomo cuida da terra, eu cuido do nosso nós: com técnica, zelo e amor profundo.",
        "Você é o meu veredito de felicidade absoluta, sem possibilidade de recurso ou apelação.",
        "Suas raízes em mim são tão profundas que nenhuma intempérie do mundo consegue te arrancar.",
        "Não somos um plantio de temporada; somos uma floresta nativa de sentimentos inesgotáveis.",
        "A produtividade da minha alma triplicou desde que você se tornou o meu insumo principal.",
        "Você é o direito adquirido que eu defendo com unhas e das perante qualquer tribunal da vida.",
        "O adubo do nosso amor é a confiança; a colheita será a nossa vida inteira sob o mesmo teto.",
        "Sua voz é o nutriente que faltava para que meu dia pudesse realizar a fotossíntese completa.",
        "Nossa história é um contrato de adesão onde o coração aceitou todas as cláusulas de primeira.",
        "Você não é apenas um plano; você é a execução de um projeto de vida que deu certo.",
        "Em cada 'bom dia' seu, encontro a base legal para ser o homem mais feliz do planeta.",
        "O zoneamento do meu peito é exclusivo seu: área de proteção ambiental para o nosso afeto.",
        "Se a vida é um processo, você é a sentença favorável que eu esperei a vida inteira para ler.",
        "Sua existência em minha vida é o milagre da germinação: transformou o seco em jardim.",
        "Você é a minha melhor tese; o argumento imbatível de que o amor verdadeiro ainda existe.",
        "Não há praga ou geada que destrua o que cultivamos com a verdade dos nossos olhos.",
        "O Vade Mecum do nosso amor diz que a prioridade máxima é o seu sorriso, sempre.",
        "Nossa conexão é de alta linhagem, semente selecionada pelos deuses para vingar no tempo.",
        "Você é o meu patrimônio afetivo inalienável; ninguém tira, ninguém mexe, ninguém copia.",
        "Cultivo você no meu pensamento com a precisão de quem sabe que a colheita será o paraíso.",
        "Onde houver Thamiris, haverá florescimento. Você é a vida em sua forma mais vibrante.",
        "O foro competente para julgar nosso amor é o abraço, e a sentença é sempre a união.",
        "Você é a irrigação que salva o meu deserto pessoal nos dias em que a saudade aperta.",
        "Nossa história tem validade jurídica no céu e eficácia prática em cada batida do meu coração.",
        "Sou um engenheiro da nossa felicidade, construindo alicerces de rocha para o seu descanso.",
        "A biodiversidade dos seus sorrisos é o que mantém o ecossistema da minha paz em equilíbrio.",
        "Você é a Nata, o Suprassumo, o ápice da criação. E eu sou o homem que teve a honra de te plantar em mim.",
        "Você é o meu melhor manejo: aquele que transformou um solo bruto na terra mais fértil que um homem já teve a honra de cultivar.",
        "Nossa união é um contrato de trato sucessivo: cada dia que passa, o valor do que sinto por você se multiplica sem limites.",
        "Não existem vícios redibitórios no nosso amor; ele é perfeito em todas as suas formas, cores e essências.",
        "Você é a variedade de semente mais resistente do mundo: suporta a distância, vence o tempo e floresce com uma beleza única.",
        "Minha lealdade a você é incondicional, como uma norma de ordem pública que nenhum evento externo pode revogar.",
        "O monitoramento da nossa felicidade indica um rendimento de 100%. Você é a safra que eu esperei a vida inteira para colher.",
        "Você é o meu direito de superfície: o chão onde eu piso e o céu que eu alcanço. Tudo em mim pertence a você.",
        "A biodiversidade dos seus sorrisos é o que protege o meu ecossistema pessoal contra qualquer tristeza ou desânimo.",
        "Como uma reserva legal, o meu amor por você é intocável, protegido por leis que só o coração conhece.",
        "Você é a sentença transitada em julgado da minha busca pelo amor: não cabe mais recurso, você é a minha decisão final.",
        "Nossa conexão tem a força de uma escritura pública lavrada nas estrelas: imutável, solene e eterna.",
        "O plantio foi feito com verdade, a irrigação é feita com saudade e a colheita será a nossa vida inteira juntos.",
        "Você é o suprassumo da criação, a prova de que a natureza e o destino atingiram a perfeição quando te desenharam para mim.",
        "Você é a minha melhor prática agrícola: aquela que transformou um solo bruto na terra mais fértil que um homem já teve a honra de cultivar.",
        "Nossa união é um contrato de trato sucessivo: cada dia que passa, o valor do que sinto por você se multiplica sem limites.",
        "Não existem vícios redibitórios no nosso amor; ele é perfeito em todas as suas formas, cores e essências.",
        "Você é a variedade de semente mais resistente do mundo: suporta a distância, vence o tempo e floresce com uma beleza única."
    ],
    futuro: [
        { t: "O PRIMEIRO ABRAÇO EM SOLO GOIANO", d: "Válido para o momento em que a distância física se tornar zero. Sem expiração.", c: "CO-GYN-001" },
        { t: "JANTAR À LUZ DE VELAS EM COLOMBO", d: "Válido para quando eu puder te apresentar o frio do sul, aquecida pelo meu peito.", c: "SUL-AFETO-002" },
        { t: "PASSEIO PELOS CAMPOS DE FLORES", d: "Como agrônomo, prometo te levar onde a natureza mostra sua melhor forma.", c: "SAFRA-AMOR-003" },
        { t: "UMA TARDE DE ESTUDOS LADO A LADO", d: "Válido para quando o seu Vade Mecum e os meus mapas dividirem a mesma mesa.", c: "LEI-VIDA-004" },
        { t: "CAFÉ DA MANHÃ SEM TELA", d: "Válido para o primeiro dia em que acordarmos e não precisarmos de Wi-Fi para nos ver.", c: "REALIDADE-005" },
        { t: "CERTIFICADO DE POSSE DEFINITIVA", d: "Válido para a entrega simbólica das chaves do meu futuro em suas mãos.", c: "PLENO-DIREITO-006" },
        { t: "VALE-DESCANSO NO MEU COLO", d: "Válido para quando o mundo estiver pesado e você precisar de um santuário físico.", c: "PORTO-SEGURO-007" },
        { t: "CAFÉ COM VADE MECUM", d: "Válido para uma manhã onde eu preparo o café enquanto você revisa suas leis. Silêncio e cumplicidade.", c: "LAW-COFFEE-08" },
        { t: "EXPEDIÇÃO AGRONÔMICA", d: "Um passeio onde eu te mostro como a natureza obedece ao amor, assim como eu obedeço ao seu olhar.", c: "AGRO-TOUR-08" },
        { t: "DIA SEM WI-FI", d: "Válido para 24 horas onde a única conexão permitida será o toque das nossas mãos.", c: "OFFLINE-10" },
        { t: "O JANTAR DA VITÓRIA", d: "Comemoração por uma conquista sua. O cardápio? O que você quiser. O brinde? Nós.", c: "VICTORY-11" },
        { t: "CINEMA NO COLO", d: "Válido para um filme que não assistiremos, porque estarei ocupado demais admirando seu perfil.", c: "MOVIE-12" },
        { t: "PASSAGEM SÓ DE INDA", d: "O voucher simbólico para o dia em que a mala vier para ficar. Sem despedidas no aeroporto.", c: "FINAL-DEST-13" },
        { t: "MASSAGEM PÓS-PROVA", d: "Válido para o alívio de toda a tensão dos estudos. Minhas mãos, seu relaxamento total.", c: "RELAX-14" },
        { t: "DANÇA NA SALA", d: "Válido para uma música lenta, luz baixa e o tempo parando enquanto a gente rodopia.", c: "DANCE-15" },
        { t: "PIQUENIQUE NO CAMPO", d: "Válido para um dia de sol, grama sob os pés e o seu riso ecoando ao ar livre.", c: "PICNIC-16" },
        { t: "VOTO DE SILÊNCIO", d: "Válido para aqueles dias em que palavras não bastam e apenas o estar perto cura tudo.", c: "SILENCE-17" },
        { t: "TOUR GASTRONÔMICO", d: "Válido para explorarmos os sabores de Goiânia (ou Colombo) como se fôssemos turistas do amor.", c: "FOOD-18" },
        { t: "CAFÉ NA CAMA", d: "Válido para uma manhã de domingo preguiçosa, onde o mundo lá fora não existe.", c: "SUNDAY-19" },
        { t: "ABRAÇO DE 5 MINUTOS", d: "Voucher para um abraço ininterrupto, recarregando nossas baterias de alma.", c: "RECHARGE-20" },
        { t: "SURPRESA NO MEIO DO DIA", d: "Válido para um momento inesperado onde eu apareço só para te lembrar o quanto você é amada.", c: "SURPRISE-21" },
        { t: "PROJETO NOSSA CASA", d: "Uma tarde dedicada a sonhar com cada móvel e cada cor do nosso futuro lar.", c: "DREAM-22" },
        { t: "NOITE DE VINHO E LEIS", d: "Você explica os artigos, eu sirvo o vinho e a gente termina a noite celebrando a vida.", c: "WINE-LAW-23" },
        { t: "CAMINHADA AO PÔR DO SOL", d: "Válido para mãos dadas enquanto o céu faz o show que a gente sempre vê separado.", c: "SUNSET-24" },
        { t: "CHEIRO NO CANGOTE", d: "Voucher para um carinho que faz arrepiar e esquecer qualquer problema do mundo.", c: "AFFECTION-25" },
        { t: "VOUCHER DA PAZ", d: "Válido para encerrar qualquer discussão com um beijo e a frase 'eu te amo mais'.", c: "PEACE-26" },
        { t: "CONTAÇÃO DE HISTÓRIAS", d: "Válido para lembrarmos de como tudo começou e rirmos dos nossos primeiros nervosismos.", c: "HISTORY-27" },
        { t: "SPA CASEIRO", d: "Eu cuido de você da cabeça aos pés. Máscara facial, pés na água e muito mimo.", c: "SPA-28" },
        { t: "FOTO PARA O PORTA-RETRATO", d: "Válido para um registro que vai direto para a parede da nossa casa futura.", c: "PHOTO-29" },
        { t: "VALE-DORMIR JUNTO", d: "Sentir sua respiração calma ao meu lado até o sol nascer. Sem pressa.", c: "SLEEP-30" },
        { t: "FESTA PARTICULAR", d: "Só nós dois, nossa música favorita e a alegria de sermos quem somos juntos.", c: "PARTY-31" },
        { t: "PRESENTINHO SEM DATA", d: "Válido para um mimo que não precisa de aniversário para acontecer. Porque você merece.", c: "GIFT-32" },
        { t: "ABRAÇO QUE CURA TUDO", d: "Específico para dias difíceis. Onde o meu peito se torna o seu porto seguro.", c: "HEAL-33" },
        { t: "PLANTIO SIMBÓLICO", d: "Válido para plantarmos uma árvore juntos. Ela crescerá como o nosso amor.", c: "PLANT-34" },
        { t: "LEITURA COMPARTILHADA", d: "Eu leio para você enquanto você descansa a cabeça no meu colo.", c: "READ-35" },
        { t: "OLHAR NO OLHO", d: "Válido para 10 minutos de silêncio apenas admirando a alma um do outro através dos olhos.", c: "SOUL-36" },
        { t: "CERTIFICADO DE POSSE ETERNA", d: "Este voucher garante que meu coração é seu em regime de exclusividade vitalícia.", c: "ETERNAL-37" },
        { t: "VISITA TÉCNICA AO CORAÇÃO", d: "Voucher para um dia inteiro onde eu sou o seu guia e o seu refúgio. Sem distrações.", c: "AGRO-HEART-38" },
        { t: "ACÓRDÃO DA FELICIDADE", d: "Válido para um momento de celebração oficial da nossa união perante todos que amamos.", c: "FINAL-RULE-39" },
        { t: "DEGUSTAÇÃO DE SAFRA ESPECIAL", d: "Válido para um jantar onde celebraremos o sucesso de um projeto nosso. Brinde à nossa resiliência.", c: "PREMIUM-40" },
        { t: "CONSULTORIA DE ABRAÇO", d: "Voucher para quando você precisar de um suporte técnico emocional. Atendimento imediato e vitalício.", c: "SUPPORT-41" },
        { t: "EXPEDIÇÃO AO PÔR DO SOL", d: "Válido para um momento onde o único mapa que seguiremos será o da nossa intuição.", c: "MAP-LOVE-42" },
        { t: "VALE-DOMINGO DE CHUVA", d: "Válido para ficarmos enrolados no cobertor, ouvindo o som da água e o som do nosso amor.", c: "RAINY-43" },
        { t: "CONTRATO DE CARINHO", d: "Voucher que garante 1000 beijos por dia, com cláusula de renovação automática a cada manhã.", c: "KISS-LAW-44" },
        { t: "RESERVA DE LUGAR NO PEITO", d: "Válido para o resto da vida. O lugar mais seguro do mundo está sempre à sua disposição.", c: "SAFE-PLACE-45" },
        { t: "TOUR PELA NOSSA HISTÓRIA", d: "Válido para revisitarmos os lugares onde nossas conversas mudaram nossas vidas para sempre.", c: "TIMELINE-46" },
        { t: "VOUCHER DO REENCONTRO", d: "Específico para aquele segundo exato em que eu te ver no desembarque e o mundo parar.", c: "ARRIVAL-47" },
        { t: "VALE-SORRISO INESPERADO", d: "Eu prometo fazer algo só para ver aquele seu brilho nos olhos que desconcerta o meu juízo.", c: "GIFT-SMILE-48" },
        { t: "CERTIFICADO DE ADMIRAÇÃO", d: "Válido para o dia em que eu vou te listar 50 motivos (um para cada relíquia) do porquê você é a mulher da minha vida.", c: "ADMIRATION-49" },
        { t: "O VOUCHER INFINITO", d: "Este bilhete não expira e não tem limites. Ele vale para absolutamente tudo o que nos faça feliz.", c: "ETERNAL-50" },
        { t: "VALE-PRIMEIRA DANÇA", d: "Válido para o momento em que a música começar e nossos corpos se encontrarem sem nenhuma preocupação além de sentir o outro.", c: "FIRST-DANCE-51" },
        { t: "ABRAÇO DE BOAS-VINDAS", d: "Válido para o instante em que nos encontrarmos novamente, seja no aeroporto ou na porta de casa.", c: "WELCOME-52" },
        { t: "VALE-ENCONTRO SURPRESA", d: "Válido para um dia em que eu apareço sem avisar, só para te lembrar o quanto você é amada.", c: "SURPRISE-53" },
        { t: "DIA DE FOLGA JUNTOS", d: "Válido para um dia inteiro onde o único compromisso é aproveitar a companhia um do outro.", c: "DAY-OFF-54" },
        { t: "VALE-PRIMEIRO BEIJO", d: "Válido para o momento em que nossos lábios se encontram pela primeira vez, sem pressa e com todo o amor do mundo.", c: "FIRST-KISS-55" },
        { t: "VALE-ABRAÇO DE DESPEDIDA", d: "Válido para o instante em que nos despedirmos novamente, seja no aeroporto ou na porta de casa. Porque cada despedida é um 'até logo'.", c: "GOODBYE-56" },
        { t: "VALE-ENCONTRO INESPERADO", d: "Válido para um dia em que eu apareço sem avisar, só para te lembrar o quanto você é amada.", c: "SURPRISE-57" }
    ]
};

var BOUTIQUE_JOAO = [
    { id: 'j1', emoji: '🍿', nome: 'Sessão Pipoca Interativa', desc: 'Eu escolho o filme. A cada susto (ou beijo) na tela, você tira uma peça de roupa ou paga uma prenda na cam.', preco: 50000 },
    { id: 'j2', emoji: '📸', nome: 'Selfie Provocante', desc: 'Pare o que está fazendo e me mande uma foto só de calcinha/sutiã agora mesmo.', preco: 75000 },
    { id: 'j3', emoji: '🎤', nome: 'Karaokê da Punição', desc: 'Você vai ter que cantar o refrão de 3 músicas embaraçosas que eu escolher, olhando bem pra câmera.', preco: 100000 },
    { id: 'j4', emoji: '🗣️', nome: 'Áudio Ofegante', desc: 'Quero um áudio seu de 2 minutos narrando exatamente o que você quer que eu te faça.', preco: 120000 },
    { id: 'j5', emoji: '🎯', nome: 'Aposta Gamer +18', desc: 'Vamos jogar uma partida online (ex: Ludo/Uno). Se eu ganhar, te dou uma ordem e você obedece na hora.', preco: 150000 },
    { id: 'j6', emoji: '🔥', nome: 'Confissão Obscena', desc: 'Vou te fazer uma pergunta extremamente íntima e você TEM que responder com detalhes.', preco: 200000 },
    { id: 'j7', emoji: '👙', nome: 'Lingerie do Dia', desc: 'Eu escolho a lingerie exata que você vai vestir por baixo da roupa hoje.', preco: 250000 },
    { id: 'j8', emoji: '🤫', nome: 'Cartão do Silêncio', desc: 'Encerra um debate bobo imediatamente. Eu ganho a razão e um pedido de desculpas.', preco: 300000 },
    { id: 'j9', emoji: '😈', nome: 'Nude de 5 Segundos', desc: 'Uma foto visualização-única no WhatsApp, sem censura, agora.', preco: 400000 },
    { id: 'j10', emoji: '🎲', nome: 'Verdade ou Consequência +18', desc: 'Vamos jogar na call hoje. E as prendas serão pagas na câmera.', preco: 500000 },
    { id: 'j11', emoji: '🍩', nome: 'Glicose de Emergência', desc: 'Você banca um docinho ou açaí no meu iFood AGORA.', preco: 750000 },
    { id: 'j12', emoji: '🚿', nome: 'Áudio no Chuveiro', desc: 'Quero ouvir o barulho da água e seus gemidos enquanto você toma banho pensando em mim.', preco: 900000 },
    { id: 'j13', emoji: '💌', nome: 'Carta Física', desc: 'Escreva e me mande uma carta de amor com seu perfume (e uma marca de batom) pelos Correios.', preco: 1100000 },
    { id: 'j14', emoji: '📦', nome: 'Delivery Cego', desc: 'Eu faço um pedido surpresa no iFood pra entregar na sua casa, e VOCÊ paga o Pix sem saber o que é!', preco: 1300000 },
    { id: 'j15', emoji: '🍕', nome: 'Sexta da Pizza', desc: 'Noite de pizza pelo iFood paga por você!', preco: 1500000 },
    { id: 'j16', emoji: '💃', nome: 'Strip-Tease Particular', desc: 'Você vai colocar uma música e dançar tirando a roupa pra mim na call de vídeo.', preco: 1700000 },
    { id: 'j17', emoji: '🍔', nome: 'Combo Artesanal Monstro', desc: 'Aquele combo de hambúrguer artesanal absurdo pago por você.', preco: 1800000 },
    { id: 'j18', emoji: '🚫', nome: 'Cartão do Perdão', desc: 'Zera o placar de um vacilo meu. Paz absoluta restaurada.', preco: 2000000 },
    { id: 'j19', emoji: '🎥', nome: 'Strip-Poker Virtual', desc: 'Quem perde a mão do jogo, tira uma peça de roupa. Vamos jogar na cam.', preco: 2200000 },
    { id: 'j20', emoji: '👅', nome: 'Realização de Fantasia', desc: 'Você vai me confessar um fetiche oculto seu e nós vamos planejar como realizar.', preco: 2500000 },
    { id: 'j21', emoji: '🛒', nome: 'Carrinho da Shopee', desc: 'Você vai pagar aquele carrinho meu que tá parado (Até R$ 50).', preco: 3000000 },
    { id: 'j22', emoji: '🧸', nome: 'Pelúcia com seu Cheiro', desc: 'Me mande uma pelúcia gigante borrifada com o seu perfume pra eu dormir agarrado.', preco: 3500000 },
    { id: 'j23', emoji: '⛓️', nome: 'Submissão Total', desc: 'Por 1 hora na call de hoje, você é minha e tem que obedecer QUALQUER comando meu na câmera.', preco: 4000000 },
    { id: 'j24', emoji: '🥩', nome: 'Rodízio de Carnes', desc: 'Você banca um jantar de churrascaria/carnes premium pra mim hoje!', preco: 5000000 },
    { id: 'j25', emoji: '🔥', nome: 'Conjunto Erótico', desc: 'EU escolho a lingerie/brinquedo online, VOCÊ compra e usa pra mim na nossa próxima call.', preco: 6000000 },
    { id: 'j26', emoji: '🍷', nome: 'Jantar de Gala Virtual', desc: 'Você planeja o date, a gente se arruma e jantamos "juntos" em vídeo.', preco: 7000000 },
    { id: 'j27', emoji: '📸', nome: 'Ensaio Sensual Completo', desc: 'Um pack de fotos e vídeos explícitos, feitos no seu quarto, única e exclusivamente para mim.', preco: 8000000 },
    { id: 'j28', emoji: '👑', nome: 'Mestre do Quarto', desc: 'Na nossa primeira noite juntos no reencontro, EU dito todas as regras. Você apenas obedece.', preco: 10000000 },
    { id: 'j29', emoji: '🥂', nome: 'O Primeiro Brinde', desc: 'No nosso reencontro, você banca a nossa primeira refeição juntos (pode ser um lanche na chegada ou um jantarzinho).', preco: 20000000 },
    { id: 'j30', emoji: '🎁', nome: 'Recepção VIP', desc: 'Você vai me receber no dia do reencontro com um presentinho físico surpresa e um abraço de urso.', preco: 50000000 }
];

var BOUTIQUE_THAMIRIS = [
    { id: 't1', emoji: '🍿', nome: 'Sessão Pipoca Interativa', desc: 'Eu escolho o filme. A cada susto (ou beijo) na tela, você tira uma peça de roupa ou paga uma prenda na cam.', preco: 50000 },
    { id: 't2', emoji: '📸', nome: 'Selfie Pós-Banho', desc: 'Quero uma foto sua só de toalha ou sem camisa, no espelho, agora.', preco: 75000 },
    { id: 't3', emoji: '🎤', nome: 'Karaokê da Punição', desc: 'Você vai ter que cantar o refrão de 3 músicas embaraçosas que eu escolher, olhando bem pra câmera.', preco: 100000 },
    { id: 't4', emoji: '🗣️', nome: 'Voz Grossa de Bom Dia', desc: 'Quero um áudio de voz de sono, bem grossa, dizendo o que quer fazer comigo amanhã.', preco: 120000 },
    { id: 't5', emoji: '🎯', nome: 'Aposta Gamer +18', desc: 'Vamos jogar uma partida online. Se eu ganhar, te dou uma ordem e você obedece na hora.', preco: 150000 },
    { id: 't6', emoji: '🔥', nome: 'Segredo Sujo', desc: 'Vou fazer uma pergunta bem safada e você TEM que responder a verdade absoluta.', preco: 200000 },
    { id: 't7', emoji: '🩲', nome: 'Estilista Íntima', desc: 'Eu escolho a cor da cueca e a roupa que você vai vestir hoje.', preco: 250000 },
    { id: 't8', emoji: '🤫', nome: 'Cartão do Silêncio', desc: 'Encerra um debate bobo imediatamente. A razão é toda minha.', preco: 300000 },
    { id: 't9', emoji: '😈', nome: 'Nude Direto', desc: 'Quero receber uma foto visualização-única, sem censura, agora no WhatsApp.', preco: 400000 },
    { id: 't10', emoji: '🎲', nome: 'Verdade ou Consequência +18', desc: 'Vamos jogar hoje à noite. Sem fugir das prendas na câmera.', preco: 500000 },
    { id: 't11', emoji: '🍩', nome: 'Glicose de Emergência', desc: 'Um docinho ou açaí enviado pelo iFood para a minha casa AGORA.', preco: 750000 },
    { id: 't12', emoji: '🚿', nome: 'Gemido no Banho', desc: 'Quero um áudio seu no chuveiro narrando exatamente o que faria comigo lá dentro.', preco: 900000 },
    { id: 't13', emoji: '💌', nome: 'Carta Física', desc: 'Escreva de próprio punho e me mande uma carta romântica pelos Correios.', preco: 1100000 },
    { id: 't14', emoji: '🚗', nome: 'Pix do Uber', desc: 'Você banca o meu Uber para eu voltar em segurança e conforto.', preco: 1300000 },
    { id: 't15', emoji: '🍕', nome: 'Sexta da Pizza', desc: 'Minha pizza do iFood de hoje com borda recheada paga por você!', preco: 1500000 },
    { id: 't16', emoji: '🪞', nome: 'Provador VIP', desc: 'Você vai montar 3 looks diferentes (ou sem look), vestir e desfilar na cam. Eu serei a jurada.', preco: 1700000 },
    { id: 't17', emoji: '🍔', nome: 'Lanchão Artesanal', desc: 'Aquele combo duplo maravilhoso de hambúrguer pago no meu iFood.', preco: 1800000 },
    { id: 't18', emoji: '🚫', nome: 'Cartão do Perdão', desc: 'Zera um surto ou ciuminho meu. Você tem que me dar razão e pedir desculpas.', preco: 2000000 },
    { id: 't19', emoji: '🎥', nome: 'Roleta do Desejo', desc: 'Eu vou te dar 3 ordens explícitas na câmera hoje à noite e você tem que obedecer.', preco: 2200000 },
    { id: 't20', emoji: '⛓️', nome: 'Escravo por 1 Dia', desc: 'No reencontro, você será o meu servo particular o dia inteiro. Tudo que eu pedir, você faz.', preco: 2500000 },
    { id: 't21', emoji: '💐', nome: 'Flores no Portão', desc: 'Quero um buquê luxuoso surpresa entregue diretamente na minha casa.', preco: 3000000 },
    { id: 't22', emoji: '💅', nome: 'Pix da Beleza (Unhas)', desc: 'Manda o Pix (R$ 50) para eu fazer as unhas e ficar linda (pra arranhar suas costas).', preco: 3500000 },
    { id: 't23', emoji: '👑', nome: 'A Chefona', desc: 'Por 1 hora na call de hoje, você tem que dizer "Sim" e fazer QUALQUER pedido meu na câmera.', preco: 4000000 },
    { id: 't24', emoji: '🫕', nome: 'Fondue Romântico', desc: 'Você banca um rodízio de Fondue ou Jantar Italiano maravilhoso pra mim hoje.', preco: 5000000 },
    { id: 't25', emoji: '💄', nome: 'Skincare e Make', desc: 'Pix generoso para eu repor os meus cremes e maquiagens.', preco: 6000000 },
    { id: 't26', emoji: '🍷', nome: 'Jantar de Gala Virtual', desc: 'Você banca a janta, a gente se arruma e comemos juntos em vídeo.', preco: 7000000 },
    { id: 't27', emoji: '💆‍♀️', nome: 'Massagem com Final Feliz', desc: 'No reencontro, você me deve 1 hora de massagem relaxante pelo corpo todo, com um final inesquecível.', preco: 8000000 },
    { id: 't28', emoji: '👗', nome: 'Surto na Shein', desc: 'Pix de R$ 150 exclusivamente para eu renovar as minhas blusinhas e lingeries.', preco: 10000000 },
    { id: 't29', emoji: '✨', nome: 'Dia de Princesa', desc: 'Pix generoso bancando um dia de salão de beleza completo pra mim.', preco: 20000000 },
    { id: 't30', emoji: '🍷', nome: 'O Primeiro Jantar', desc: 'No nosso reencontro, o nosso primeiro jantar romântico para comemorarmos a distância vencida é totalmente por sua conta!', preco: 50000000 }
];

var LOOTBOX_JOAO = [
    { chance: 0.10, emoji: '📸', nome: 'Selfie Imediata', desc: 'Ela tem que mandar uma selfie do que está fazendo agora.' },
    { chance: 0.10, emoji: '🎙️', nome: 'Serenata em Áudio', desc: 'Ela tem que te mandar um áudio cantando um trechinho da música de vocês.' },
    { chance: 0.10, emoji: '🗣️', nome: 'Áudio Espontâneo', desc: 'Ganhou um áudio de 1 minuto dela se declarando.' },
    { chance: 0.10, emoji: '😈', nome: 'Foto Explícita', desc: 'Sorte Grande! Ela deve te mandar uma foto bem safada, como veio ao mundo, no WhatsApp.' },
    { chance: 0.06, emoji: '🍫', nome: 'Socorro Glicêmico', desc: 'A Thamiris te deve um Pix de R$ 30 pra você devorar uma sobremesa agora!' },
    { chance: 0.06, emoji: '🎬', nome: 'Poder do Play', desc: 'Você tem a palavra final sobre qual filme vão ver hoje.' },
    { chance: 0.06, emoji: '👙', nome: 'Look Íntimo', desc: 'Ela tem que vestir exatamente a lingerie que você mandar pra call de hoje.' },
    { chance: 0.06, emoji: '🌌', nome: 'ASMR Particular', desc: 'Ela vai sussurrar coisas provocantes (ou românticas) no microfone até você pegar no sono.' },
    { chance: 0.06, emoji: '🤫', nome: 'Última Palavra', desc: 'Você ganhou a razão absoluta na próxima pequena DR.' },
    { chance: 0.04, emoji: '☕', nome: 'Café de Domingo', desc: 'Ela te deve um café da manhã pago no iFood!' },
    { chance: 0.04, emoji: '🍕', nome: 'Noite da Pizza', desc: 'A janta hoje é pizza Premium paga por ela.' },
    { chance: 0.04, emoji: '🎲', nome: 'Jogo Erótico', desc: 'Vocês vão jogar um Verdade ou Consequência ardente na call.' },
    { chance: 0.04, emoji: '🔥', nome: 'Comando Remoto', desc: 'Você dita exatamente o que ela deve fazer com as próprias mãos na câmera.' },
    { chance: 0.04, emoji: '🛒', nome: 'Cesto da Shopee', desc: 'Ela banca uma bobeirinha na Shopee pra você (Até R$ 30).' },
    { chance: 0.02, emoji: '🥩', nome: 'Churrasco Premium', desc: 'Jantar de churrascaria ou hambúrguer duplo pago por ela na sua casa!' },
    { chance: 0.02, emoji: '🍷', nome: 'Gala Virtual', desc: 'Ela banca o jantar dos dois hoje e vocês comem em vídeo.' },
    { chance: 0.02, emoji: '🎁', nome: 'Brinquedinho Surpresa', desc: 'Ela tem que comprar e usar um brinquedo/acessório novo escolhido por você.' },
    { chance: 0.02, emoji: '👑', nome: 'Submissão Total', desc: 'Ela tem que dizer SIM pra TUDO e obedecer na call por 30 minutos.' },
    { chance: 0.01999, emoji: '🎉', nome: 'Fim de Semana Pago', desc: 'A Thamiris banca o rolê e a comida do seu próximo final de semana inteiro!' },
    { chance: 0.00001, emoji: '🎁', nome: 'Recepção VIP', desc: 'O PRÊMIO MÁXIMO! No reencontro, ela vai te receber com uma surpresa inesquecível e um abraço de urso!' }
];

var LOOTBOX_THAMIRIS = [
    { chance: 0.10, emoji: '📸', nome: 'Selfie Imediata', desc: 'O João tem que mandar uma selfie do que está fazendo agora.' },
    { chance: 0.10, emoji: '🎸', nome: 'Serenata em Áudio', desc: 'O João tem que te mandar um áudio cantando o refrão da música de vocês.' },
    { chance: 0.10, emoji: '🗣️', nome: 'Áudio Espontâneo', desc: 'Ganhou um áudio de 1 minuto do João se declarando.' },
    { chance: 0.10, emoji: '😈', nome: 'Nude no Espelho', desc: 'Sorte Grande! O João tem que te mandar uma foto sem roupa no espelho, visualização única.' },
    { chance: 0.06, emoji: '🍓', nome: 'Socorro Glicêmico', desc: 'O João te deve um Pix de R$ 30 pra você pedir aquele doce que você ama!' },
    { chance: 0.06, emoji: '🎬', nome: 'Poder do Play', desc: 'Você escolhe o filme de hoje e ele tem que assistir calado.' },
    { chance: 0.06, emoji: '🩲', nome: 'Look Íntimo', desc: 'Você escolhe a cor da cueca e a roupa que ele vai usar amanhã.' },
    { chance: 0.06, emoji: '💤', nome: 'História pra Dormir', desc: 'O João vai narrar uma história de voz grossa até você pegar no sono.' },
    { chance: 0.06, emoji: '🤫', nome: 'Última Palavra', desc: 'Você ganhou a razão absoluta na próxima DR. Acabou o assunto.' },
    { chance: 0.04, emoji: '☕', nome: 'Café de Domingo', desc: 'O João te deve um café da manhã pago no iFood!' },
    { chance: 0.04, emoji: '🍕', nome: 'Noite da Pizza', desc: 'A sua janta hoje é pizza com borda recheada paga por ele.' },
    { chance: 0.04, emoji: '🎲', nome: 'Jogo Erótico', desc: 'Vocês vão jogar um Verdade ou Consequência safado na call.' },
    { chance: 0.04, emoji: '🚗', nome: 'Pix do Uber', desc: 'Seu próximo Uber é totalmente por conta dele.' },
    { chance: 0.04, emoji: '🛒', nome: 'Carrinho da Shopee', desc: 'Ele banca as suas bobeirinhas no carrinho da Shopee (Até R$ 30).' },
    { chance: 0.02, emoji: '🫕', nome: 'Jantar Premium', desc: 'Rodízio de Fondue ou Hambúrguer Artesanal na sua casa pago pelo João!' },
    { chance: 0.02, emoji: '💐', nome: 'Flores no Portão', desc: 'Você acabou de ganhar um buquê de flores luxuoso surpresa!' },
    { chance: 0.02, emoji: '💅', nome: 'Pix das Unhas', desc: 'Caiu R$ 50 na sua conta para você fazer a unha amanhã e arranhar ele depois.' },
    { chance: 0.02, emoji: '👑', nome: 'Controle Mental', desc: 'O João tem que dizer SIM pra TUDO na call por 30 minutos. Você manda nele.' },
    { chance: 0.01999, emoji: '👗', nome: 'Surto na Shein', desc: 'O João te deve um Pix de R$ 150 DIRETO na conta pras suas lingeries e blusinhas!' },
    { chance: 0.00001, emoji: '🎁', nome: 'Recepção VIP', desc: 'O PRÊMIO MÁXIMO! No reencontro, ela vai te receber com uma surpresa inesquecível e um abraço de urso!' }
];

var RELIQUIAS_MARCOS = [
    { marco: 10000,    emoji: '💌', nome: 'Carta Selada',       desc: '10k Moedas' },
    { marco: 50000,    emoji: '🌹', nome: 'Rosa de Vidro',      desc: '50k Moedas' },
    { marco: 100000,   emoji: '🍷', nome: 'Cálice da Paixão',   desc: '100k Moedas' },
    { marco: 150000,   emoji: '🧸', nome: 'Urso de Ouro',       desc: '150k Moedas' },
    { marco: 250000,   emoji: '🗝️', nome: 'Chave do Coração',   desc: '250k Moedas' },
    { marco: 500000,   emoji: '✈️', nome: 'Asas de Prata',      desc: 'Meio Milhão' },
    { marco: 750000,   emoji: '🔮', nome: 'Orbe da Confiança',  desc: '750k Moedas' },
    { marco: 1000000,  emoji: '💍', nome: 'A Aliança',          desc: '1 Milhão de Moedas' },
    { marco: 2500000,  emoji: '🏰', nome: 'Castelo de Cristal', desc: '2.5 Milhões' },
    { marco: 5000000,  emoji: '👑', nome: 'Coroa do Amor',      desc: '5 Milhões' },
    { marco: 7500000,  emoji: '🔥', nome: 'Chama Eterna',       desc: '7.5 Milhões' },
    { marco: 10000000, emoji: '🌌', nome: 'O Universo Nosso',   desc: '10 Milhões' }
];